apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - internalhttps
  routes:
    - kind: Rule
      match: Host(`{{ .Values.dns.host }}`) && PathPrefix(`/prometheus`)
      services:
        - kind: Service
          name: prometheus-stack-prometheus
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 9090