apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
spec:
  entryPoints:
    - internalhttps
  routes:
    - kind: Rule
      match: Host(`{{ .Values.dns.host }}`) && PathPrefix(`/alertmanager`)
      middlewares:
        - name: strip-prefix-{{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: prometheus-stack-alertmanager
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 9093